### PR TITLE
Parse records of containers using volatile overlay mounts

### PR DESCRIPTION
**Pull request by yadneshk**
This change adds support to parse records from "volatile-containers.json" while holds the records for containers created with "--rm" flag.

### CODE REVIEW

**Review by leifmadsen — COMMENTED** [review]
I give this a +1, but defer approval as I am not a core for golang code :)

**Comment by csibbitt** [comment]
Can you please include a reference to the issue you are trying to solve? The code makes sense to me, but I have no other context about why this change is required.

**Comment by csibbitt** [comment]
> Can you please include a reference to the issue you are trying to solve? The code makes sense to me, but I have no other context about why this change is required.

Okay, I found it. I think it's `RHBZ: 2179071`

**Review by csibbitt — COMMENTED** [review]
LGTM. Can you please show some output that proves this solves the problem?

**Review by paramite — APPROVED** [review]

**Comment by yadneshk** [comment]
With these changes I do see ceph container records in prometheus.
```
collectd_libpodstats_pod_cpu_percent{container="sg-core", endpoint="prom-https", host="controller-0.redhat.local", plugin_instance="ceph-aef1676b-ed41-5bf7-abbd-0138af40edb5-crash-controller-0", service="default-osp17-coll-meter", type_instance="base"} | 0
collectd_libpodstats_pod_cpu_percent{container="sg-core", endpoint="prom-https", host="controller-0.redhat.local", plugin_instance="ceph-aef1676b-ed41-5bf7-abbd-0138af40edb5-mgr-controller-0-suofpq", service="default-osp17-coll-meter", type_instance="base"} | 0
collectd_libpodstats_pod_cpu_percent{container="sg-core", endpoint="prom-https", host="controller-0.redhat.local", plugin_instance="ceph-aef1676b-ed41-5bf7-abbd-0138af40edb5-mon-controller-0", service="default-osp17-coll-meter", type_instance="base"} | 0
collectd_libpodstats_pod_cpu_percent{container="sg-core", endpoint="prom-https", host="controller-0.redhat.local", plugin_instance="ceph-aef1676b-ed41-5bf7-abbd-0138af40edb5-rgw-rgw-controller-0-kimnsv", service="default-osp17-coll-meter", type_instance="base"} | 0
```

However, they all report 0.

I believe the stats for ceph services are not present under `/sys/fs/cgroup/machine.slice/libpod-<container_id>.scope` like rest of the containers.
~~~
[root@psi-standalone ~]# podman ps | grep cinder_api
84a0de11aaec  quay.io/tripleomastercentos9/openstack-cinder-api:current-tripleo   kolla_start   55 minutes ago  Up   52 minutes 
 (healthy)  cinder_api

[root@psi-standalone ~]# find /sys/fs/cgroup/ -iname "*84a0de11aaec*"
/sys/fs/cgroup/machine.slice/libpod-84a0de11aaec48ff22b64f59ee9ae88c82a5ceeb07419d850dab679bbd31a2ec.scope
~~~

~~~
[root@psi-standalone ~]# podman ps | grep ceph
e09933869000  quay.rdoproject.org/tripleomastercentos9/daemon:current-ceph                                                             -n mon.psi-standa...  2 hours ago        Up 2 hours                              ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc-mon-psi-standalone-localdomain

[root@psi-standalone ~]# find /sys/fs/cgroup/ -iname "*e09933869000*"
/sys/fs/cgroup/system.slice/system-ceph\x2d332cfe0d\x2dcd42\x2d5667\x2daa09\x2dca57970f68cc.slice/ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc@mon.psi-standalone.localdomain.service/libpod-payload-e0993386900015f6d5e863f9992ae6eab61f26c02d998cf8f26d606a617c0829
[root@psi-standalone ~]# 


$ find /sys/fs/cgroup/ -iname "*ceph*"
/sys/fs/cgroup/system.slice/system-ceph\x2d332cfe0d\x2dcd42\x2d5667\x2daa09\x2dca57970f68cc.slice/ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc@osd.0.service
/sys/fs/cgroup/system.slice/system-ceph\x2d332cfe0d\x2dcd42\x2d5667\x2daa09\x2dca57970f68cc.slice/ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc@crash.psi-standalone.service
/sys/fs/cgroup/system.slice/system-ceph\x2d332cfe0d\x2dcd42\x2d5667\x2daa09\x2dca57970f68cc.slice/ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc@mgr.psi-standalone.localdomain.fhmbba.service
/sys/fs/cgroup/system.slice/system-ceph\x2d332cfe0d\x2dcd42\x2d5667\x2daa09\x2dca57970f68cc.slice/ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc@mon.psi-standalone.localdomain.service
~~~

It seems we do not parse `system.slice` paths in https://github.com/infrawatch/collectd-libpod-stats/blob/master/pkg/virt/virt.go#L118-L129

**Comment by yadneshk** [comment]
With these changes I now see cpu and memory stats for all ceph services
```
collectd_libpodstats_pod_cpu_percent{exported_instance="psi-standalone.localdomain", instance="localhost:9103", job="prometheus", libpodstats="ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc-crash-psi-standalone"} | 0.00673863648812027
collectd_libpodstats_pod_cpu_percent{exported_instance="psi-standalone.localdomain", instance="localhost:9103", job="prometheus", libpodstats="ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc-mgr-psi-standalone-localdomain-fhmbba"} | 2.07046141385553
collectd_libpodstats_pod_cpu_percent{exported_instance="psi-standalone.localdomain", instance="localhost:9103", job="prometheus", libpodstats="ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc-mon-psi-standalone-localdomain"} | 0.524719513481891
collectd_libpodstats_pod_cpu_percent{exported_instance="psi-standalone.localdomain", instance="localhost:9103", job="prometheus", libpodstats="ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc-osd-0"} | 2.78210611165564
```
```
collectd_libpodstats_pod_memory{exported_instance="psi-standalone.localdomain", instance="localhost:9103", job="prometheus", libpodstats="ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc-crash-psi-standalone"} | 7561216
collectd_libpodstats_pod_memory{exported_instance="psi-standalone.localdomain", instance="localhost:9103", job="prometheus", libpodstats="ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc-mgr-psi-standalone-localdomain-fhmbba"} | 510521344
collectd_libpodstats_pod_memory{exported_instance="psi-standalone.localdomain", instance="localhost:9103", job="prometheus", libpodstats="ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc-mon-psi-standalone-localdomain"} | 420204544
collectd_libpodstats_pod_memory{exported_instance="psi-standalone.localdomain", instance="localhost:9103", job="prometheus", libpodstats="ceph-332cfe0d-cd42-5667-aa09-ca57970f68cc-osd-0"} | 1317822464
```

**Review by csibbitt — APPROVED** [review]

**Review by leifmadsen — APPROVED** [review]

**Pull request merged**
